### ISSUE TITLE
Connection failure with basic HTTP authentication

### ISSUE THREAD

**Issue by Boyfinn** [gpvigano/VidStreamComp#3]
I'm trying to connect to my stream which is protected with basic HTTP authentication, but my connection fails using the IPCameraStream.cs script. I get two identical errors when attempting to connect:
`Failed to connect to IP camera: System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure`
However, the stream connects just fine if i disable authentication from my streaming server.
Authentication works just fine on my browser, this issue only occurs when attempting a connection with login credentials in Unity.

**Comment by gpvigano** [comment]
There is a new commit that should solve this issue (sorry for the late reply).
Let me know if it works for you now.
